ppw/ppw/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index, time

urlpatterns = [
    path('', index),
    path('time/', time),
    path('time/<int:offset>', time),
    path('story1/', include("story1.urls", namespace="story1")),
    path('story3/', include("story3.urls", namespace="story3")),
    path('story5/', include("story5.urls", namespace="story5")),
    path('story6/', include("story6.urls", namespace="story6")),
    path('admin/', admin.site.urls),
]

ppw/story1/urls.py
from django.urls import path
from . import views

app_name = "story1"

urlpatterns = [
    path('', views.index, name="index")
]

ppw/story3/urls.py
from django.urls import path
from . import views

app_name = "story3"

urlpatterns = [
    path("", views.index, name="index")
]

ppw/story5/urls.py
from django.urls import path, re_path
from .views import kelas, index, kelas_s

app_name="story5"

urlpatterns = [
    path('api/kelas/<int:id>', kelas),
    path('api/kelas/', kelas),
    path('', index, name="index"),
    path('<int:id>/', kelas_s),
]

ppw/story6/urls.py
from django.urls import path
from . import views

app_name = "story6"

urlpatterns = [
    path('', views.index, name="index"),
    path('remove/<int:id>', views.remove, name="remove"),
    path('tambah/', views.tambahKegiatan, name="tambah")
]

ppw/story1/models.py
from django.db import models

# Create your models here.

ppw/story3/models.py
from django.db import models

# Create your models here.

ppw/story5/models.py
from django.db import models
from django.forms import ModelForm
from django import forms

from .customfields import RangedIntegerField

class Kelas(models.Model):
    nama = models.CharField(blank=False, max_length=100)
    dosen = models.CharField(max_length=100, blank=False)
    sks = RangedIntegerField(blank=False, min_value=1, max_value=6)
    deskripsi = models.TextField()
    semester = models.CharField(max_length=20, blank=False)
    kelas = models.CharField(max_length=20, blank=False)

    def __str__(self):
        return f"<{self.nama}>"

class Tugas(models.Model):
    kelas = models.ForeignKey('Kelas', on_delete=models.CASCADE)
    nama = models.CharField(max_length=20, blank=False)
    deskripsi = models.TextField()
    deadline = models.DateTimeField()

class TugasForm(ModelForm):
    model = Tugas
    fields = ['nama', 'deskripsi', 'deadline']

class KelasForm(ModelForm):
    class Meta:
        model = Kelas
        fields = ['nama', 'dosen', 'sks', 'deskripsi', 'semester', 'kelas']

    def clean_nama(self):
        data = self.cleaned_data.get('nama')
        if Kelas.objects.filter(nama=data):
            raise forms.ValidationError(f"The class {data} is already registered.")
        return data

ppw/story6/models.py
from django.db import models
from django.forms import ModelForm


class Peserta(models.Model):
    nama = models.CharField(max_length=20)


class Kegiatan(models.Model):
    nama = models.CharField(max_length=20)
    desk = models.TextField()
    peserta = models.ManyToManyField(Peserta, blank=True)


class KegiatanForm(ModelForm):
    class Meta:
        model = Kegiatan
        fields = ['nama', 'desk']

ppw/ppw/views.py
from django.shortcuts import render
from dateutil.parser import parse
import datetime

# Create your views here.
def index(request):
  return render(request, "index.html")

def time(request, offset=0):
    tzobj = datetime.datetime.now(datetime.timezone.utc).astimezone()
    info = tzobj.tzinfo
    context = {
        "value": tzobj,
    }
    return render(request, "time.html", context=context)

ppw/story1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
  return render(request, "./story1/index.html")

ppw/story3/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "story3/index.html")

ppw/story5/views.py
from django.views.decorators.http import require_http_methods
from django.core.serializers import serialize
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from django.http import JsonResponse
import requests
import json

from .models import Kelas, KelasForm
from .encoder import ExtendedEncoder

# Create your views here.
@require_http_methods(["GET", "POST", "DELETE"])
@csrf_exempt
def kelas(request, id=None):
    # @POST
    if request.method == "POST":
        try:
            res = json.loads(request.body)
            if Kelas.objects.filter(nama=res['nama']):
                raise Exception(f"The class {res['nama']} is already registered") 
            newKelas = Kelas(**res)
            newKelas.save()

            newKelas = json.loads(serialize('json', [newKelas]))[0]
            res = {"success": True, "data": {"pk": newKelas['pk'], "fields": newKelas['fields']}}
        except Exception as e:
            res = {"success": False, "error": str(e)}

        return JsonResponse(res, safe=False, json_dumps_params={'indent': 2})

    # @DELETE
    if request.method == "DELETE":
        res = {}
        if not id:
            res['success'] = False
            res['error'] = "No id specified"
        else:
            getKelas = Kelas.objects.filter(pk=id)
            if not getKelas:
                res['success'] = False
                res['error'] = "No class with that id"
            else:
                res['success'] = True
                res['data'] = list(getKelas)
                getKelas.delete()

        return JsonResponse(res, safe=False, encoder=ExtendedEncoder, json_dumps_params={"indent": 2})

    # @GET
    if id:
        getData = Kelas.objects.filter(pk=id)
        newData = json.loads(serialize('json', getData))
        for idx in range(len(getData)):
            data = json.loads(serialize('json', list(getData[idx].tugas_set.all())))
            for i in range(len(data)):
                data[i] = data[i]['fields']
            newData[idx]['fields']['tugas'] = data
            newData[idx]['fields']['id'] = newData[idx]['pk']
            newData[idx] = newData[idx]['fields']

        if not list(getData):
           return JsonResponse({"success": False, "error": "No class with that id"}, json_dumps_params={'indent': 2}) 
    else:
        getData = list(Kelas.objects.all())
        newData = json.loads(serialize('json', getData))
        for idx in range(len(getData)):
            data = json.loads(serialize('json', list(getData[idx].tugas_set.all())))
            for i in range(len(data)):
                data[i] = data[i]['fields']
            newData[idx]['fields']['tugas'] = data
            newData[idx]['fields']['id'] = newData[idx]['pk']
            newData[idx] = newData[idx]['fields']
    return JsonResponse({"success": True, "data": newData}, safe=False, encoder=ExtendedEncoder, json_dumps_params={"indent": 2})


def index(request):
    form = KelasForm()
    r  = requests.get("https://ppw-zakbil.herokuapp.com/story5/api/kelas")
    if request.method == "POST":
        form = KelasForm(request.POST)
        if form.is_valid():
            form.save()

    context = {
        "data": r.json(),
        "form": form
    }

    return render(request, "story5/index.html", context)
def kelas_s(request, id):
    if id:
        r = requests.get(f"https://ppw-zakbil.herokuapp.com/story5/api/kelas/{id}")
    else:
        redirect("story5.index")

    return render(request, 'story5/kelas.html', {"data": r.json()})

ppw/story6/views.py
from django.shortcuts import render, redirect
from .models import Kegiatan, Peserta, KegiatanForm


def index(request):
    getKegiatan = Kegiatan.objects.all()

    if request.method == "POST":
        keg = Kegiatan.objects.filter(pk=int(request.POST['id'])).first()
        nam = Peserta.objects.filter(nama=request.POST['nama'])
        if not nam:
            x = Peserta(nama=request.POST['nama'])
            x.save()
            keg.peserta.add(x)
            keg.save()
        else:
            keg.peserta.add(nam.first())
            keg.save()
        redirect('story6.views.index')

    context = {
       "data": getKegiatan,
    }

    return render(request, 'story6/index.html', context)


def remove(request, id):
    rem = Peserta.objects.filter(pk=id).first()
    kegi = request.GET.get('kegi', '')

    keg = Kegiatan.objects.filter(pk=int(kegi)).first()
    keg.peserta.remove(rem)
    keg.save()

    return redirect('story6:index')


def tambahKegiatan(request):
    getKegiatan = Kegiatan.objects.all()
    form = KegiatanForm()

    if request.method == "POST":
        form = KegiatanForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/story6/')

    context = {
       "data": getKegiatan,
       "form": form
    }

    return render(request, 'story6/index.html', context)

ppw/ppw/templates/ppw/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'ppw/css/normalize.css' %}" />
    {% block head %}{% endblock head %}
</head>

<body>
    {% block content %} {% endblock %}
    {% block script %} {% endblock %}
</body>

</html>

ppw/ppw/templates/ppw/index.html
{% extends "base.html" %}
{% load static %}

{% block title %} Welcome Page {% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'ppw/css/main.css' %}">
{% endblock head %}

{% block content %}
{% include 'navbar.html' %}
{% endblock content %}

ppw/ppw/templates/ppw/navbar.html
<div class="nav">
    <div class="nav-container">
        <ul>
            <li><a href="{% url 'story1:index' %}">Story 1</a></li>
            <li><a href="{% url 'story3:index' %}">Story 3</a></li>
            <li><a href="{% url 'story5:index' %}">Story 5</a></li>
        </ul>
        <h3>NAVBAR INI DARI INCLUDE LHOOO</h3>
    </div>
</div>

ppw/ppw/templates/ppw/time.html
{% extends "base.html" %}
{% load static %}
{% load tz %}

{% block title %} THIS PAGE DISPLAYS TIME {% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'ppw/css/main.css' %}">
{% endblock head %}

{% block content %}
{% include 'navbar.html' %}
{{ value }}
{% endblock content %}

ppw/story1/templates/story1/index.html
{% extends "base.html" %}
{% load static %}

{% block title %} My Profile {% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'story1/css/index.css' %}" />
{% endblock head %}

{% block content %}
<div class="container">
    <div class="kiri">
        <div class="box__fixed-wrapper">
            <div class="box__wrapper">
                <div class="box">
                    <div class="box__heading">
                        <h1 class="box__header">
                            Halo,
                            <br />
                            nama saya <br /> <span>Zaky Bilfagih</span> :)
                        </h1>
                        <p class="box__subheader">
                            Bisa dipanggil 'Zaky' atau 'Zakbil', suka bermain
                            tenis meja, senang membuat hal yang seru terutama
                            yang terkait dengan teknologi
                        </p>
                    </div>
                    <div class="box__navigation">
                        <label for="nav_mahasiswa">
                            <input type="radio" name="navigation" id="nav_mahasiswa" checked />
                            <a href="#mahasiswa" onClick="handleClick(this)">
                                Profil
                            </a>
                        </label>
                        <label for="nav_pendidikan">
                            <input type="radio" name="navigation" id="nav_pendidikan" />
                            <a href="#pendidikan" onClick="handleClick(this)">
                                Riwayat Pendidikan
                            </a>
                        </label>
                    </div>
                    <div class="box__social">
                        <div class="box__socialcontainer">
                            <p><a href="https://github.com/mackarelfish" target="_blank">Github</a></p> |
                            <p><a href="https://twitter.com/zakybilfagih" target="_blank">Twitter</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="kanan">
        <div class="page mahasiswa" id="mahasiswa">
            <div class="mahasiswa__content">
                <h1 class="mahasiswa__contentheader">Profil</h1>
                <div class="mahasiswa__contentcontainer">
                    <ul>
                        <li>Nama: <span>Muhammad Zaki</span></li>
                        <li>NPM: <span>190640002</span></li>
                        <li>Angkatan: <span>Maung 2019</span></li>
                        <li>Kampus: <span>Universitas Indonesia</span></li>
                    </ul>
                    <img src="{% static 'story1/img/prof.jpg' %}" alt="profile image" class="mahasiswa__contentimg">
                </div>
            </div>
        </div>
        <div class="page pendidikan" id="pendidikan">
            <div class="pendidikan__content">
                <h1 class="pendidikan__contentheader">Riwayat Pendidikan</h1>
                <div class="pendidikan__contentcontainer">
                    <ul>
                        <li>Universitas Indonesia <span>(2019 - 2023)</span></li>
                        <li>SMAN 34 Jakarta <span>(2016 - 2019)</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
<script type="text/javascript">
    // handle click a tag to trigger radio input
    function handleClick(e) {
        e.previousElementSibling.checked = true;
    }

    (() => {
        // get all content with class page
        const items = document.querySelectorAll(".page");
        const options = {
            root: null,
            rootMargin: "-50%",
            treshold: 1.0
        };
        const observer = new IntersectionObserver((entries, observer) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    let id = entry.target.id;
                    let inp = document.querySelector(`#nav_${id}`);
                    inp.checked = true;
                }
            });
        }, options);

        items.forEach(item => {
            observer.observe(item);
        });
    })();

</script>
{% endblock script %}

ppw/story3/templates/story3/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tailwind Starter Template</title>
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <link
            href="{% static 'story3/style.5d31f88f.css' %}"
            rel="stylesheet"
        />
    </head>
    <body>
        <div
            class="flex flex-col h-screen items-stretch md:flex-row md:items-stretch"
        >
            <nav
                class="flex flex-col self-center max-w-xs py-6 mx-8 md:self-stretch md:w-full lg:max-w-sm lg:h-full"
            >
                <div class="flex flex-col justify-between flex-1">
                    <div class="self-center">
                        <h1
                            class="inline-block text-2xl w-full pb-3 md:text-left md:text-5xl"
                        >
                            Halo,
                            <br />
                            nama saya
                            <br />
                            Zaky Bilfagih :)
                        </h1>
                        <p
                            class="hidden md:block text-xs md:text-base xl:text-lg"
                        >
                            Bisa dipanggil 'Zaky' atau 'Zakbil', suka bermain
                            tenis meja, senang membuat hal yang seru terutama
                            yang terkait dengan teknologi
                        </p>
                        <ul
                            class="flex flex-col text-lg md:text-xl xl:text-2xl mt-4"
                        >
                            <li><a href="#profil">Profil</a></li>
                            <li><a href="#riwayat">Riwayat Pendidikan</a></li>
                        </ul>
                    </div>
                    <div
                        class="flex text-lg md:text-xl xl:text-2xl self-center mt-6 md:self-start"
                    >
                        <p>Github</p>
                        <span class="px-2">|</span>
                        <p>Twitter</p>
                    </div>
                </div>
            </nav>
            <div class="bg-red-400 flex-auto overflow-y-scroll smooth">
                <div
                    class="flex flex-col container h-full w-full md:h-screen justify-center items-center bg-yellow-400"
                    id="profil"
                >
                    <h1 class="text-2xl mb-1">Profil</h1>
                    <div class="flex bg-gray-500">
                        <div class="flex items-center px-4 w-64">
                            <ul>
                                <li>Nama: Muhammad Zaky</li>
                                <li>NPM: 1906400002</li>
                                <li>Angkatan: 2019 Maung</li>
                                <li>Kampus: Universitas Indonesia</li>
                            </ul>
                        </div>
                        <img
                            src="{% static 'story3/prof.6961dcf1.jpg' %}"
                            alt=""
                            class="object-cover h-32 flex-1 w-32"
                        />
                    </div>
                </div>
                <div
                    class="bg-gray-300 flex flex-col container h-full w-full md:h-screen justify-center items-center"
                    id="riwayat"
                >
                    <h1 class="text-2xl mb-1">Riwayat Pendidikan</h1>
                    <div class="flex items-center px-4">
                        <ul>
                            <li>Universitas Indonesia (2019 - 2023)</li>
                            <li>SMAN 34 Jakarta (2016 - 2019)</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

ppw/story5/templates/story5/index.html
{% extends "base.html" %}
{% load static %}

{% block title %} Story 5 {% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'story5/css/main.css' %}">
{% endblock head %}

{% block content %}
<div>
    {% for item in data.data %}
    <div class="kelas_box">
        <div class="kelas_header">
            <div class="kelas_title">
                <h1><a href="/story5/{{ item.id }}">{{ item.nama }}</a></h1>
                <span>{{ item.sks }} sks</span>
            </div>
            <p>{{ item.semester }}</p>
        </div>
        <div class="kelas_content">
            <p>{{ item.deskripsi }}</p>
            <div class="kelas_info">
                <p>{{ item.dosen }}</p>
                <p>{{ item.kelas }}</p>
            </div>
        </div>
    </div>
    {% endfor %}

    <div>
        <form method="POST" style="display: flex; flex-direction: column; width: 50%; margin: 0 auto; min-width: 400px;">
            {% csrf_token %}
            {{ form }}
            <button type="submit">SUBMIT</button>
        </form>
    </div>
</div>
{% endblock content %}

ppw/story5/templates/story5/kelas.html
{% extends "base.html" %}
{% load static %}

{% block title %} Story 5 {% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'story5/css/main.css' %}">
{% endblock head %}

{% block content %}
{% for item in data.data %}
<div>
    <div class="kelas_box">
        <div class="kelas_header">
            <div class="kelas_title">
                <h1>{{ item.nama }}</h1>
                <span>{{ item.sks }} sks</span>
            </div>
            <p>{{ item.semester }}</p>
        </div>
        <div class="kelas_content">
            <p>{{ item.deskripsi }}</p>
            <div class="kelas_info">
                <p>{{ item.dosen }}</p>
                <p>{{ item.kelas }}</p>
            </div>
        </div>
        <div>
            {% for item in data.data %}
            {% for tugas in item.tugas %}
            <p>>{{ tugas.nama }}</p>
            <p>{{ tugas.deskripsi }}</p>
            <p>{{ tugas.deadline }}</p>
            {% endfor %}
            {% endfor %}
        </div>
    </div>
</div>
{% endfor %}
{% endblock content %}

ppw/story6/templates/story6/index.html
{% extends "base.html" %}
{% load static %}

{% block title %} Story 5 {% endblock title %}

{% block head %}
<style>
body,
html {
    height: 100%;
}

.kegiatan-container {
    display: flex;
    height: 100%;
    align-items: center;
    justify-content: center;
}

.kegiatan-list {
    display: flex;
    flex-wrap: wrap;
    max-width: 900px;
}

.kegiatan-card {
    background: red;
    margin-right: 20px;
    margin-bottom: 20px;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
}

.kegiatan-card h1 {
    margin: 0;
    text-align: center;
}

.kegiatan-card p {
    margin-top: 0px;
}

.kegiatan-tambah {
    margin-left: 20px;
}

.input-tambah {
    display: flex;
}

.input-tambah > input {
    flex: 1;
}

.tambah {
    display: flex;
    flex-direction: column;
}

@media only screen and (max-width: 600px) {
    .kegiatan-list {
        display: initial;
        flex-direction: column;
    }

    .kegiatan-container {
        margin-top: 450px;
    }
}

</style>
{% endblock head %}

{% block content %}
<div class="kegiatan-container">
    <div class="kegiatan-list">
        {% for kegiatan in data %}
        <div class="kegiatan-card">
            <h1>{{ kegiatan.nama }}</h1> 
            <p>{{ kegiatan.desk }}</p>
            <ul>
                {% for peserta in kegiatan.peserta.all %}
                <li>{{ peserta.nama }} <a href="/story6/remove/{{ peserta.pk }}?kegi={{kegiatan.pk}}"><span>x</span></a></li>
                {% endfor %}
            </ul>
            <div class="input-tambah">
                <form method="POST">
                    {% csrf_token %}
                    <input type="text" name="nama">
                    <input type="hidden" name="id" value="{{ kegiatan.pk }}">
                    <input type="submit" value="+">
                </form>
            </div>
        </div>
        {% endfor %}
        <div >
            <form method="POST" class="tambah">
                {% csrf_token %}
                {{form}}
                {% if form %}
                <input type="submit" value="submit">
                {% endif %}
            </form>
        </div>
    </div>
    <div class="kegiatan-tambah">
        <a href="/story6/tambah"><button>+</button></a>
    </div>
</div>
{% endblock content %}